// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM21iIfiIwEZmhgPdn3swStWQ8HDskq8s',
    appId: '1:324325701970:web:acbd5b037d16cb27d7a28b',
    messagingSenderId: '324325701970',
    projectId: 'flutter-tiktok-3baab',
    authDomain: 'flutter-tiktok-3baab.firebaseapp.com',
    storageBucket: 'flutter-tiktok-3baab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXnVRA-pNItFt9vgt5nsvjfv_rWiqKp4A',
    appId: '1:324325701970:android:d21a6305c696c7c7d7a28b',
    messagingSenderId: '324325701970',
    projectId: 'flutter-tiktok-3baab',
    storageBucket: 'flutter-tiktok-3baab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8hC7M_aV5h8wJJTDosNOAVCM-0XQm6BM',
    appId: '1:324325701970:ios:6027b99e94e74569d7a28b',
    messagingSenderId: '324325701970',
    projectId: 'flutter-tiktok-3baab',
    storageBucket: 'flutter-tiktok-3baab.appspot.com',
    iosBundleId: 'com.frontchen.tiktokClone',
  );
}
