// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3WN520vlkL5GXnbhC9QjnYuO9yMcZLco',
    appId: '1:878012081111:web:643fd719569de844ef6192',
    messagingSenderId: '878012081111',
    projectId: 'flutter-clone-54ea0',
    authDomain: 'flutter-clone-54ea0.firebaseapp.com',
    storageBucket: 'flutter-clone-54ea0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApLamApwuCup8vs1kpSlb74XaNrQjo7WM',
    appId: '1:878012081111:android:44facd61eb313d9def6192',
    messagingSenderId: '878012081111',
    projectId: 'flutter-clone-54ea0',
    storageBucket: 'flutter-clone-54ea0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjwbsDrTeyl1nsgJf44TqxwsZJ9BhwuwY',
    appId: '1:878012081111:ios:3ffffeb1d5fbfcf6ef6192',
    messagingSenderId: '878012081111',
    projectId: 'flutter-clone-54ea0',
    storageBucket: 'flutter-clone-54ea0.appspot.com',
    iosBundleId: 'com.frontchen.tiktokClone',
  );
}
